### ISSUE TITLE
add logo and text to header

### ISSUE THREAD

**Issue by DakuwoN** [DakuwoN/reddit#15]
I added the logo and header, but we need text. We can wrap this content in a div and use flexbox to align it properly in the header similar to the mock.... check Header.js

**Comment by Sk-223** [comment]
Used flexbox to style the header similar to our mock, [Style Guide](https://www.figma.com/file/vBRjWMJV3rQbXyJOxPPNAf/Redditz-Style-Guide?type=design&node-id=0%3A1&mode=design&t=9C6AddzJik3ZqEjj-1)

**Comment by DakuwoN** [comment]
Excellent job dookie ! You're a quick learner yo
